#!/bin/bash
# build-pkg.sh — Build a pacman package for claude-cowork-service locally
#
# Usage: build-pkg.sh [--install] <binary_path> <version> [arch]
#
# Creates claude-cowork-service-<version>-1-<arch>.pkg.tar.zst in the current
# directory. The package contains the pre-built static Go binary + systemd
# user service.
#
# arch defaults to "x86_64". Pass "aarch64" for ARM64 builds.
#
# --install   After a successful build, run `sudo pacman -U` on the package.

set -euo pipefail

INSTALL=false
POSITIONAL=()
for arg in "$@"; do
    case "$arg" in
        --install) INSTALL=true ;;
        --help|-h)
            echo "Usage: $0 [--install] <binary_path> <version> [arch]"
            exit 0
            ;;
        --*) echo "ERROR: Unknown option: $arg"; exit 1 ;;
        *) POSITIONAL+=("$arg") ;;
    esac
done
set -- "${POSITIONAL[@]}"

if [ $# -lt 2 ]; then
    echo "Usage: $0 [--install] <binary_path> <version> [arch]"
    exit 1
fi

BINARY="$1"
VERSION="$2"
TARGET_ARCH="${3:-x86_64}"

if [ ! -f "$BINARY" ]; then
    echo "ERROR: Binary not found: $BINARY"
    exit 1
fi

command -v makepkg >/dev/null 2>&1 || { echo "ERROR: makepkg not found (install pacman/pkgbuild tools)"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUT_DIR="$(pwd)"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "=== Building claude-cowork-service pacman package ==="

# Stage source files alongside PKGBUILD so makepkg can pick them up via local source=()
cp "$BINARY"                              "$WORK_DIR/cowork-svc-linux"
cp "$REPO_ROOT/claude-cowork.service"     "$WORK_DIR/claude-cowork.service"
cp "$REPO_ROOT/LICENSE"                   "$WORK_DIR/LICENSE"
cp "$REPO_ROOT/claude-cowork-service.install" "$WORK_DIR/claude-cowork-service.install"

cat > "$WORK_DIR/PKGBUILD" <<EOF
# Generated by packaging/arch/build-pkg.sh — do not edit.

pkgname=claude-cowork-service
pkgver=${VERSION}
pkgrel=1
pkgdesc="Native Linux backend for Claude Desktop Cowork (prebuilt)"
arch=('${TARGET_ARCH}')
url="https://github.com/patrickjaja/claude-cowork-service"
license=('MIT')
depends=('systemd' 'util-linux')
optdepends=('claude-desktop-bin: Unofficial Linux frontend for Claude Desktop Cowork'
            'claude-code: An agentic coding tool that lives in your terminal')
install="claude-cowork-service.install"

source=('cowork-svc-linux'
        'claude-cowork.service'
        'LICENSE'
        'claude-cowork-service.install')
sha256sums=('SKIP' 'SKIP' 'SKIP' 'SKIP')

package() {
    install -Dm755 "\$srcdir/cowork-svc-linux"          "\$pkgdir/usr/bin/cowork-svc-linux"
    install -Dm644 "\$srcdir/claude-cowork.service"     "\$pkgdir/usr/lib/systemd/user/claude-cowork.service"
    install -Dm644 "\$srcdir/LICENSE"                   "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
}
EOF

(
    cd "$WORK_DIR"
    CARCH="$TARGET_ARCH" PKGDEST="$OUT_DIR" makepkg --nodeps --skipchecksums --noconfirm -f
)

PKG_FILE=$(find "$OUT_DIR" -maxdepth 1 -name "claude-cowork-service-${VERSION}-1-${TARGET_ARCH}.pkg.tar*" -type f | head -1)
if [ -z "$PKG_FILE" ]; then
    echo "ERROR: makepkg succeeded but no package file found in $OUT_DIR"
    exit 1
fi

PKG_BASENAME=$(basename "$PKG_FILE")
SHA256=$(sha256sum "$PKG_FILE" | cut -d' ' -f1)

echo "=== Built ${PKG_BASENAME} ($(du -h "$PKG_FILE" | cut -f1)) ==="
echo "  SHA256: $SHA256"
echo ""

if [ "$INSTALL" = true ]; then
    echo "=== Installing ${PKG_BASENAME} via pacman ==="
    sudo pacman -U --noconfirm "$PKG_FILE"
else
    echo "Install with:  sudo pacman -U $PKG_BASENAME"
fi
